#!/bin/sh

# ref
# - https://git-scm.com/docs/githooks#_post_checkout
# - https://gist.github.com/lyrixx/5867424

PREV_COMMIT=$1
POST_COMMIT=$2
if [[ -f composer.lock ]]; then
    DIFF=`git diff --shortstat $PREV_COMMIT..$POST_COMMIT composer.lock`
    if [[ $DIFF != "" ]]; then
        echo "composer.lock has changed. You must run composer install"
    fi
fi
if [[ -f yarn.lock ]]; then
    DIFF=`git diff --shortstat $PREV_COMMIT..$POST_COMMIT yarn.lock`
    if [[ $DIFF != "" ]]; then
        echo "yarn.lock has changed. You must run yarn install"
    fi
fi
